name: Compiler CI

on:
  push:
    branches:
    - master

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v3.0.0
      with:
        distribution: 'temurin'
        java-version: '8'
    - name: compile and run compiler
      run: javac Compiler.java
      run: java Compiler
    - name: output ir
      run: cat ir.txt
